// Vocabulary and training data for each user profile

const VOCABULARY = {
    sports: [
        'the','a','an','is','was','are','were','be','been','being','have','has','had',
        'do','does','did','will','would','could','should','can','may','might','must',
        'to','of','in','on','at','by','for','with','from','about','as','into',
        'i','you','he','she','it','we','they','my','your','his','her','its','our','their',
        'this','that','these','those','what','which','who','when','where','why','how',
        'and','or','but','if','because','so','than','not','only','just','very','too',
        'more','most','some','any','all','each','every','no','then','now','today',
        'tomorrow','yesterday','tonight','always','never','really','quite','still',
        // Sports core
        'game','match','play','player','players','team','teams','score','scored','goal','goals',
        'win','won','lose','lost','victory','defeat','champion','championship','tournament','league',
        'season','coach','coaching','training','practice','field','court','stadium','arena','pitch',
        'ball','football','soccer','basketball','baseball','tennis','cricket','hockey','rugby',
        'volleyball','golf','swimming','running','racing','cycling','boxing','wrestling',
        'athlete','athletes','athletic','sport','sports','competition','compete','competitive',
        'pass','passed','shoot','shot','kick','kicked','throw','threw','catch','caught',
        'run','ran','sprint','sprinted','jump','jumped','dive','dived','tackle','tackled',
        'defense','offense','attack','strategy','tactics','formation','position','positions',
        'referee','umpire','penalty','foul','yellow','red','card','timeout','halftime',
        'quarter','half','period','inning','set','round','lap','race','heat','final',
        'record','world','olympic','olympics','medal','gold','silver','bronze','podium',
        'fitness','workout','exercise','gym','strength','speed','endurance','stamina','agility',
        'performance','skill','skills','technique','professional','amateur','draft','contract',
        'transfer','injury','injured','recovery','comeback','substitute','bench','captain',
        'amazing','incredible','fantastic','excellent','great','good','bad','strong','fast',
        'powerful','talented','skilled','experienced','young','veteran','star','legend',
        'crowd','fans','supporters','cheer','celebrate','celebration','trophy','title',
        'point','points','lead','leading','trailing','tied','draw','overtime','shootout',
        'serve','return','volley','smash','dribble','block','steal','rebound','assist',
        'pitcher','batter','striker','goalkeeper','defender','midfielder','forward','winger',
        'innings','over','wicket','boundary','six','four','century','fifty','hat','trick',
        'marathon','sprint','relay','hurdles','javelin','discus','shot','put','high','long',
        'freestyle','backstroke','butterfly','breaststroke','lap','pool','lane','heat',
        'knockout','round','bout','punch','jab','hook','uppercut','clinch','corner',
        'serve','ace','deuce','advantage','break','set','tiebreak','grand','slam',
        'offside','corner','free','kick','header','cross','dribble','nutmeg','volley',
        'slam','dunk','three','pointer','layup','free','throw','rebound','turnover',
        'home','run','strikeout','walk','double','triple','pitcher','catcher','outfield'
    ],

    baking: [
        'the','a','an','is','was','are','were','be','been','being','have','has','had',
        'do','does','did','will','would','could','should','can','may','might','must',
        'to','of','in','on','at','by','for','with','from','about','as','into',
        'i','you','he','she','it','we','they','my','your','his','her','its','our','their',
        'this','that','these','those','what','which','who','when','where','why','how',
        'and','or','but','if','because','so','than','not','only','just','very','too',
        'more','most','some','any','all','each','every','no','then','now','today',
        'tomorrow','yesterday','always','never','really','quite','still','about','around',
        // Baking core
        'bake','baking','baked','baker','bakery','recipe','recipes','ingredient','ingredients',
        'flour','sugar','butter','egg','eggs','milk','cream','vanilla','chocolate','cocoa',
        'yeast','salt','baking','powder','soda','cinnamon','nutmeg','ginger','cardamom',
        'honey','maple','syrup','oil','water','lemon','orange','zest','juice','extract',
        'cake','cakes','bread','loaf','cookie','cookies','pie','pastry','pastries','muffin',
        'muffins','cupcake','cupcakes','brownie','brownies','tart','tarts','scone','scones',
        'biscuit','biscuits','croissant','croissants','donut','donuts','waffle','waffles',
        'pancake','pancakes','crepe','crepes','sourdough','brioche','focaccia','ciabatta',
        'dough','batter','mix','mixture','blend','whisk','beat','fold','knead','roll',
        'cut','shape','rise','proof','ferment','rest','chill','freeze','thaw','cool',
        'oven','temperature','degrees','fahrenheit','celsius','preheat','timer','rack',
        'pan','sheet','tin','mold','bowl','mixer','spatula','whisk','sieve','grater',
        'measuring','cup','spoon','tablespoon','teaspoon','gram','ounce','pound','liter',
        'sweet','savory','delicious','tasty','flavor','taste','texture','aroma','smell',
        'moist','fluffy','crispy','crunchy','soft','tender','golden','brown','caramelized',
        'frosting','icing','glaze','filling','topping','decoration','sprinkles','ganache',
        'layer','layers','slice','slices','piece','pieces','serve','serving','portion',
        'fresh','homemade','scratch','perfect','easy','simple','quick','classic','artisan',
        'turned','came','looks','smells','needs','requires','takes','makes','yields',
        'combine','add','pour','spread','drizzle','dust','coat','brush','grease','line',
        'stiff','peaks','soft','peaks','ribbon','stage','crumb','crust','crumble','streusel',
        'caramel','toffee','fudge','truffle','mousse','custard','pudding','gelatin','agar',
        'almond','walnut','pecan','hazelnut','pistachio','coconut','raisin','cranberry',
        'strawberry','blueberry','raspberry','cherry','apple','pear','banana','mango',
        'whipped','cream','buttercream','meringue','marzipan','fondant','royal','icing',
        'sponge','chiffon','pound','angel','devil','carrot','red','velvet','black','forest'
    ],

    cs: [
        'the','a','an','is','was','are','were','be','been','being','have','has','had',
        'do','does','did','will','would','could','should','can','may','might','must',
        'to','of','in','on','at','by','for','with','from','about','as','into',
        'i','you','he','she','it','we','they','my','your','his','her','its','our','their',
        'this','that','these','those','what','which','who','when','where','why','how',
        'and','or','but','if','because','so','than','not','only','just','very','too',
        'more','most','some','any','all','each','every','no','then','now','today',
        'tomorrow','yesterday','always','never','really','quite','still','using','through',
        // CS core
        'code','coding','coded','codebase','program','programming','programmed','software','hardware',
        'computer','computers','algorithm','algorithms','data','structure','structures',
        'function','functions','method','methods','class','classes','object','objects',
        'variable','variables','constant','constants','array','arrays','list','lists',
        'dictionary','hash','map','set','string','strings','integer','float','boolean',
        'null','undefined','type','types','interface','abstract','inheritance','polymorphism',
        'javascript','python','java','cpp','csharp','ruby','php','swift','typescript',
        'rust','go','kotlin','scala','haskell','elixir','clojure','erlang','lua','perl',
        'framework','library','libraries','package','packages','module','modules','import',
        'export','require','dependency','dependencies','npm','pip','maven','gradle','cargo',
        'react','angular','vue','svelte','node','express','django','flask','spring','rails',
        'database','sql','nosql','mongodb','postgresql','mysql','redis','sqlite','cassandra',
        'api','rest','graphql','http','https','request','response','endpoint','endpoints',
        'server','client','frontend','backend','fullstack','web','mobile','desktop','cloud',
        'app','application','applications','development','developer','developers','engineer',
        'debug','debugging','debugger','bug','bugs','error','errors','exception','exceptions',
        'fix','fixes','test','testing','tests','unit','integration','e2e','coverage','mock',
        'deployment','deploy','production','staging','environment','environments','config',
        'git','github','gitlab','version','control','commit','commits','push','pull','merge',
        'branch','branches','repository','repo','clone','fork','issue','issues','pr','review',
        'docker','kubernetes','container','containers','microservice','microservices','devops',
        'aws','azure','gcp','lambda','serverless','cdn','load','balancer','nginx','apache',
        'machine','learning','ai','artificial','intelligence','neural','network','networks',
        'model','models','training','dataset','datasets','feature','features','label','labels',
        'optimization','performance','memory','cpu','gpu','thread','threads','process','async',
        'await','promise','promises','callback','callbacks','event','loop','stack','heap',
        'compiled','runs','works','executes','returns','takes','needs','handles','processes',
        'refactor','refactoring','clean','readable','maintainable','scalable','efficient',
        'syntax','semantic','runtime','compile','interpreter','transpile','minify','bundle',
        'cache','caching','session','token','authentication','authorization','oauth','jwt',
        'encryption','hashing','security','vulnerability','injection','xss','csrf','cors',
        'responsive','accessibility','seo','performance','lighthouse','webpack','vite','babel',
        'component','components','state','props','hooks','context','reducer','store','action',
        'query','mutation','subscription','schema','resolver','middleware','pipeline','stream'
    ]
};

const TRAINING_DATA = {
    sports: [
        // ── game / match ──
        'the game was amazing yesterday',
        'the game is starting soon',
        'the game ended in victory',
        'the game was very competitive',
        'the game went into overtime',
        'the game attracted thousands of fans',
        'the game was broadcast live tonight',
        'the game finished with a draw',
        'the game had incredible moments',
        'the game was decided by penalty',
        'the match was incredibly intense',
        'the match ended in a draw',
        'the match was postponed due to rain',
        'the match will be played tomorrow',
        'the match had five goals scored',
        'the match was watched by millions',
        'the match lasted ninety minutes',
        'the match was decided in overtime',
        // ── team ──
        'our team won the championship',
        'our team is playing very well',
        'our team will win today',
        'our team has great players',
        'our team needs more practice',
        'our team scored three goals',
        'our team defended brilliantly today',
        'our team is training every morning',
        'the team celebrated their victory',
        'the team has excellent chemistry',
        'the team played with great passion',
        'the team won the league title',
        'the team lost due to injuries',
        'the team is preparing for finals',
        'the team has a new coach',
        'the team signed a star player',
        // ── player / athlete ──
        'the player scored three goals',
        'the player is very talented',
        'the player has incredible speed',
        'the player was injured yesterday',
        'the player made an amazing pass',
        'the player broke the world record',
        'the player transferred to a new club',
        'the player signed a big contract',
        'the player recovered from injury',
        'the player is the team captain',
        'the athlete broke the world record',
        'the athlete is training very hard',
        'the athlete will compete next week',
        'the athlete has amazing endurance',
        'the athlete won the gold medal',
        'the athlete recovered from injury quickly',
        'the athlete is preparing for olympics',
        'the athlete set a new record',
        // ── training / practice ──
        'training session starts at six',
        'training session is very important',
        'training session was productive today',
        'training session helps improve skills',
        'training every morning builds endurance',
        'training hard leads to victory',
        'training with the team is essential',
        'training improves speed and strength',
        'practice makes the team stronger',
        'practice session was very intense',
        'practice helps players improve technique',
        'practice every day to get better',
        // ── coach / strategy ──
        'the coach announced a new strategy',
        'the coach is very experienced',
        'the coach will make changes',
        'the coach has great tactics',
        'the coach was pleased with performance',
        'the coach changed the formation',
        'the coach motivated the players',
        'the coach has a winning strategy',
        'the strategy worked perfectly today',
        'the strategy was changed at halftime',
        'the tactics were very effective',
        'the formation was changed by coach',
        // ── football / soccer ──
        'football match is tomorrow night',
        'football match will be broadcast live',
        'football match ended in a draw',
        'football season starts next month',
        'football player scored a hat trick',
        'football team won the league',
        'football is the most popular sport',
        'football requires skill and fitness',
        'soccer player scored an amazing goal',
        'soccer player transferred to new club',
        'soccer team is training every day',
        'soccer match was very exciting',
        'soccer requires great teamwork',
        'soccer ball was kicked perfectly',
        'the goal was scored in injury time',
        'the goal was absolutely incredible',
        'the goal was disallowed by referee',
        'the goalkeeper made an amazing save',
        'the goalkeeper blocked the penalty kick',
        'the goalkeeper is very experienced',
        // ── basketball ──
        'basketball tournament begins next week',
        'basketball player dunked the ball',
        'basketball team won the championship',
        'basketball game went into overtime',
        'basketball requires speed and agility',
        'basketball player scored thirty points',
        'basketball match was very exciting',
        'the slam dunk was incredible',
        'the three pointer won the game',
        'the rebound was grabbed perfectly',
        // ── tennis ──
        'tennis match lasted five sets',
        'tennis player served an ace',
        'tennis tournament is very prestigious',
        'tennis requires great concentration',
        'tennis player won the grand slam',
        'tennis match was incredibly intense',
        'the serve was very powerful',
        'the return was perfectly placed',
        // ── running / marathon ──
        'running marathon requires great endurance',
        'running marathon is very challenging',
        'running every morning improves fitness',
        'running builds strength and stamina',
        'marathon runner finished in record time',
        'marathon training takes months of work',
        'the sprint was incredibly fast',
        'the race was very competitive',
        'the race ended in a photo finish',
        'the runner broke the world record',
        // ── olympics ──
        'olympic games are very exciting',
        'olympic games will start soon',
        'olympic games showcase athletic excellence',
        'olympic medal is a great achievement',
        'olympic athlete trained for years',
        'the gold medal was won today',
        'the silver medal was a great result',
        'the bronze medal was well deserved',
        // ── injury / recovery ──
        'sports injury requires proper recovery time',
        'the player is recovering from injury',
        'the injury was not very serious',
        'recovery from injury takes several weeks',
        'the player returned from injury today',
        // ── stadium / fans ──
        'the stadium was packed with fans',
        'the stadium has a great atmosphere',
        'the crowd cheered for the team',
        'the fans celebrated the victory',
        'the supporters were very loud today',
        // ── score / result ──
        'the score was tied at halftime',
        'the score is very close now',
        'the score reflects team performance',
        'the final score was three nil',
        'the score changed in the last minute',
        // ── cricket ──
        'cricket world cup starts in june',
        'cricket player scored a century',
        'cricket match lasted five days',
        'cricket team won by ten wickets',
        'cricket requires patience and skill',
        'the batsman hit a six',
        'the bowler took five wickets',
        'the innings was very impressive',
        // ── hockey / rugby / volleyball ──
        'hockey team won the gold medal',
        'hockey player scored the winning goal',
        'rugby match was physically demanding',
        'rugby player tackled very hard',
        'volleyball serve was absolutely perfect',
        'volleyball team won the tournament',
        // ── golf / swimming ──
        'golf tournament played in beautiful weather',
        'golf player made an incredible shot',
        'swimming competition was very close',
        'swimming requires great technique',
        'the swimmer broke the world record',
        // ── fitness / gym ──
        'fitness training improves athletic performance',
        'fitness training is essential every day',
        'gym workout builds strength and endurance',
        'exercise every day to stay fit',
        'strength training helps prevent injuries',
        // ── general sports phrases ──
        'i like sports very much',
        'i like football and basketball',
        'i like watching games live',
        'i like playing soccer every day',
        'i like competitive sports always',
        'i like training every morning',
        'i like running marathons regularly',
        'i like team sports the best',
        'i like championship tournaments always',
        'i enjoy watching football matches',
        'i enjoy playing basketball with friends',
        'i enjoy training at the gym',
        'i enjoy competitive sports events',
        'i enjoy watching the olympics',
        'sports is my favorite hobby',
        'sports keeps me fit and healthy',
        'sports teaches teamwork and discipline',
        'sports requires dedication and hard work',
        'playing sports is very enjoyable',
        'watching sports is very exciting',
        'the penalty kick was perfectly executed',
        'the free kick was scored directly',
        'the corner kick led to a goal',
        'the offside trap worked perfectly',
        'the substitution changed the game',
        'the captain led the team brilliantly',
        'the defense was very strong today',
        'the offense scored three times',
        'the goalkeeper saved the penalty',
        'the referee made a controversial call',
        'professional athletes train every single day',
        'professional athletes are very dedicated',
        'professional athletes have rigorous schedules',
        'the competition was fierce and intense',
        'the competition has many participants',
        'the championship was won decisively',
        'the trophy was lifted by the captain',
        'the title was defended successfully',
        'the league table shows our team first',
        'the transfer window opens next month'
    ],

    baking: [
        // ── cake ──
        'the cake turned out perfectly moist',
        'the cake is cooling on the rack',
        'the cake will be decorated later',
        'the cake has three layers',
        'the cake was delicious yesterday',
        'the cake looks absolutely beautiful',
        'the cake smells wonderful today',
        'the cake needs more frosting',
        'the cake baked for thirty minutes',
        'the cake rose perfectly in the oven',
        'the cake crumb is very tender',
        'the cake layers are even and flat',
        'the cake is ready to be sliced',
        'the cake was a huge success',
        'the cake recipe is very simple',
        // ── bread ──
        'baking bread requires patience and practice',
        'baking bread is very rewarding',
        'baking bread has a wonderful aroma',
        'baking bread takes several hours',
        'baking bread needs proper kneading',
        'the bread dough needs to rise',
        'the bread is baking in the oven',
        'the bread came out golden brown',
        'the bread has a crispy crust',
        'the bread smells amazing right now',
        'the bread was sliced and served',
        'the bread loaf is perfectly shaped',
        'sourdough bread has a tangy flavor',
        'sourdough starter needs daily feeding',
        'sourdough bread takes longer to make',
        'artisan bread has a complex flavor',
        'artisan bread is very crusty outside',
        'artisan bread takes time to perfect',
        // ── cookies ──
        'chocolate chip cookies are my favorite',
        'chocolate chip cookies smell amazing',
        'chocolate chip cookies taste delicious',
        'chocolate chip cookies were perfect yesterday',
        'the cookies spread too much unfortunately',
        'the cookies are perfectly crispy',
        'the cookies have chocolate chunks',
        'the cookies were baked yesterday',
        'the cookies need more baking time',
        'the cookies came out of the oven',
        'the cookie dough was chilled overnight',
        'the cookie recipe uses brown sugar',
        'baking cookies is very satisfying',
        'cookies should be soft in the middle',
        'cookies taste best when still warm',
        // ── dough / batter ──
        'the dough needs to rise overnight',
        'the dough is very sticky today',
        'the dough will double in size',
        'the dough has risen perfectly',
        'the dough was kneaded thoroughly',
        'the dough should rest for an hour',
        'the dough requires more flour',
        'the dough is ready to be shaped',
        'the batter is smooth and creamy',
        'the batter should not be overmixed',
        'the batter was poured into the pan',
        'the batter has the right consistency',
        'mix the batter until just combined',
        'the batter needs one more egg',
        // ── oven / temperature ──
        'preheat the oven to three fifty',
        'preheat the oven before baking',
        'preheat the oven for best results',
        'the oven temperature is very important',
        'the oven needs to be preheated',
        'baking temperature affects final texture',
        'baking temperature is very important',
        'the oven was set to three hundred',
        'the oven timer went off now',
        'the oven is ready for baking',
        'bake at three fifty for thirty minutes',
        'bake until golden brown on top',
        'bake the bread for forty minutes',
        'bake the cookies for twelve minutes',
        // ── mixing / technique ──
        'mix flour and sugar in a bowl',
        'mix flour with butter carefully',
        'mix flour until well combined',
        'mix flour and eggs together',
        'whisk butter and sugar until fluffy',
        'whisk butter with eggs thoroughly',
        'whisk the cream until stiff peaks',
        'fold the egg whites gently in',
        'fold the flour into the batter',
        'knead the dough for ten minutes',
        'knead the dough until smooth',
        'knead the dough on a floured surface',
        'cream the butter and sugar together',
        'cream the butter until light and fluffy',
        'beat the eggs until well combined',
        'beat the mixture for two minutes',
        'sift the flour before adding it',
        'sift the dry ingredients together',
        // ── ingredients ──
        'vanilla extract adds wonderful flavor',
        'vanilla extract is an essential ingredient',
        'vanilla extract has a strong aroma',
        'baking soda helps cakes rise properly',
        'baking soda is an important ingredient',
        'baking powder makes the cake fluffy',
        'fresh ingredients make all the difference',
        'fresh ingredients have better flavor',
        'measuring ingredients accurately is very important',
        'measuring ingredients carefully ensures success',
        'the recipe calls for two eggs',
        'the recipe calls for one cup flour',
        'the recipe calls for half cup sugar',
        'the recipe calls for unsalted butter',
        'add the vanilla extract now',
        'add the eggs one at a time',
        'add the flour gradually to batter',
        'add the butter to the mixture',
        'add the sugar and mix well',
        'add the chocolate chips last',
        // ── frosting / decoration ──
        'frosting should be smooth and creamy',
        'frosting is too thick right now',
        'frosting will be piped on top',
        'frosting has the perfect consistency',
        'frosting needs more powdered sugar',
        'the buttercream frosting is very smooth',
        'the cream cheese frosting is delicious',
        'the chocolate ganache is very rich',
        'the glaze was drizzled on top',
        'the icing was applied carefully',
        'decorate the cake with fresh berries',
        'decorate the cupcakes with sprinkles',
        // ── muffins / cupcakes ──
        'the muffins came out golden brown',
        'the muffins are still warm now',
        'the muffins have blueberries inside',
        'the muffins were baked perfectly',
        'the muffins smell delicious right now',
        'the cupcakes need decorative frosting',
        'the cupcakes are cooling down now',
        'the cupcakes will be decorated later',
        'the cupcakes have vanilla flavor',
        'the cupcakes were baked today',
        // ── pie / tart ──
        'the pie crust was perfectly flaky',
        'the pie crust is very delicate',
        'the pie crust has butter layers',
        'the pie crust was rolled very thin',
        'the pie filling is sweet and tangy',
        'the pie needs to cool completely',
        'the tart filling was smooth and creamy',
        'the tart has a lemon flavor',
        'the tart shell is very crispy',
        // ── scones / pastries ──
        'the scones were light and tender',
        'the scones are best served warm',
        'the scones have a buttery flavor',
        'the scones were baked fresh today',
        'cinnamon rolls smell absolutely amazing',
        'cinnamon rolls are still baking now',
        'cinnamon rolls have a sweet filling',
        'cinnamon rolls were served warm today',
        'croissants are very flaky and buttery',
        'croissants take a long time to make',
        // ── brownies ──
        'chocolate brownies are incredibly delicious',
        'chocolate brownies have a fudgy texture',
        'chocolate brownies were enjoyed yesterday',
        'the brownies came out perfectly today',
        'the brownies are very rich and dense',
        'the brownies need to cool before cutting',
        // ── general baking phrases ──
        'i like baking cakes every weekend',
        'i like making cookies for everyone',
        'i like fresh bread in the morning',
        'i like chocolate desserts the most',
        'i like homemade pastries always',
        'i like decorating cupcakes creatively',
        'i like trying new baking recipes',
        'i like baking from scratch always',
        'i enjoy baking delicious cakes',
        'i enjoy making fresh bread daily',
        'i enjoy decorating beautiful cupcakes',
        'i enjoy creating sweet desserts',
        'baking is my favorite hobby',
        'baking from scratch is very rewarding',
        'baking from scratch tastes much better',
        'homemade pastries taste much better',
        'homemade bread is very satisfying',
        'the recipe is very easy to follow',
        'the recipe yields twelve servings',
        'the recipe needs some adjustments',
        'layer cake requires careful assembly',
        'layer cake has a cream filling',
        'layer cake was decorated beautifully',
        'the sponge cake is very light',
        'the pound cake is very dense',
        'the carrot cake has cream cheese frosting',
        'the red velvet cake is very popular',
        'proper mixing technique prevents lumps',
        'proper mixing technique is very essential',
        'bakery quality results are achievable at home',
        'fresh out of the oven is best',
        'let the cake cool before frosting',
        'let the bread cool before slicing',
        'the kitchen smells amazing right now',
        'the aroma of fresh bread is wonderful',
        'the smell of cookies is incredible',
        'baking makes the house smell wonderful'
    ],

    cs: [
        // ── code / programming ──
        'the code compiled without any errors',
        'the code is running smoothly now',
        'the code will be deployed tomorrow',
        'the code has been tested thoroughly',
        'the code was refactored yesterday',
        'the code works perfectly now',
        'the code needs more optimization',
        'the code requires better documentation',
        'the code is very clean and readable',
        'the code follows best practices',
        'the code was reviewed by the team',
        'the code has no bugs now',
        'the code is well structured',
        'the code needs to be refactored',
        'writing clean code is very important',
        'writing code every day improves skills',
        // ── debugging ──
        'debugging this issue took several hours',
        'debugging this problem is very challenging',
        'debugging the error was difficult',
        'debugging the code took a long time',
        'the bug was fixed this morning',
        'the bug was very hard to find',
        'the bug caused the application to crash',
        'the error message was very helpful',
        'the error was caught by the tests',
        'the exception was handled properly',
        'the exception was thrown unexpectedly',
        'fixing the bug improved performance',
        // ── algorithm / data structure ──
        'the algorithm has linear time complexity',
        'the algorithm is very efficient',
        'the algorithm will be optimized',
        'the algorithm was designed carefully',
        'the algorithm works correctly now',
        'the algorithm needs better performance',
        'sorting algorithm runs in n log n',
        'binary search is very efficient',
        'the data structure is very efficient',
        'the data structure was implemented correctly',
        'linked list is a basic data structure',
        'hash map provides constant time lookup',
        'binary tree is used for searching',
        'graph algorithms are very complex',
        // ── function / class ──
        'the function returns a boolean value',
        'the function is very useful here',
        'the function will be called later',
        'the function has been tested thoroughly',
        'the function takes two parameters',
        'the function needs better documentation',
        'the function handles edge cases well',
        'the class was designed with inheritance',
        'the class has multiple methods',
        'the method returns the correct value',
        'the method was refactored today',
        'the object was instantiated correctly',
        // ── javascript / python ──
        'javascript framework makes development easier',
        'javascript is very popular for web',
        'javascript runs in the browser',
        'javascript has many useful libraries',
        'python is great for data science',
        'python is very easy to learn',
        'python has many powerful libraries',
        'python code is very readable',
        'python is used for machine learning',
        'python script runs very fast',
        'typescript adds type safety to javascript',
        'typescript is very popular now',
        // ── react / frontend ──
        'react components should be reusable',
        'react components are very flexible',
        'react hooks simplify state management',
        'react is very popular for frontend',
        'react component was created today',
        'the component renders correctly now',
        'the component has a state update',
        'the state was updated correctly',
        'the props were passed correctly',
        'frontend framework improves user experience',
        'frontend code was refactored today',
        'the user interface looks very clean',
        // ── api / backend ──
        'the api returns json formatted data',
        'the api is working correctly now',
        'the api will be documented soon',
        'the api has many endpoints',
        'the api was deployed yesterday',
        'the api needs better error handling',
        'rest api follows standard conventions',
        'graphql api is very flexible',
        'the endpoint returns the correct data',
        'the request was handled successfully',
        'the response was sent to the client',
        'backend api provides necessary endpoints',
        'backend code was optimized today',
        'the server handles thousands of requests',
        'the server is running smoothly now',
        'the server will be upgraded soon',
        'the server needs more resources',
        // ── database ──
        'database query needs proper optimization',
        'database query is running very slow',
        'database query returns correct results',
        'the database was migrated successfully',
        'the database has many tables',
        'sql query was optimized today',
        'nosql database is very scalable',
        'mongodb stores data as documents',
        'postgresql is very reliable database',
        'the query runs in constant time',
        'the index improved query performance',
        // ── git / version control ──
        'git commit message must be descriptive',
        'git commit was pushed to main',
        'the pull request was reviewed today',
        'the pull request was merged successfully',
        'the branch was created for feature',
        'the repository has many open issues',
        'the repository is very active now',
        'version control is essential for teams',
        'the merge conflict was resolved today',
        'the code review was very helpful',
        // ── testing ──
        'unit tests ensure code quality',
        'unit tests are very important',
        'unit tests will be written today',
        'unit tests have all passed now',
        'unit tests cover all edge cases',
        'the test suite passed completely',
        'the test failed due to a bug',
        'integration tests verify the system',
        'writing tests improves code quality',
        'test driven development is very effective',
        // ── machine learning / ai ──
        'machine learning model requires training data',
        'machine learning model is very accurate',
        'machine learning model will be deployed',
        'machine learning model was improved yesterday',
        'machine learning algorithm works very well',
        'neural network achieved high accuracy',
        'neural network is very complex',
        'neural network has many layers',
        'artificial intelligence transforms modern technology',
        'artificial intelligence is very powerful',
        'artificial intelligence has many applications',
        'deep learning model was trained today',
        'the model accuracy improved significantly',
        'the dataset was preprocessed carefully',
        'the training data was split correctly',
        'the model was deployed to production',
        // ── docker / cloud / devops ──
        'docker container runs the application',
        'docker container is very lightweight',
        'docker container was built successfully',
        'cloud deployment completed successfully today',
        'cloud deployment is very fast now',
        'kubernetes manages the containers well',
        'the microservice was deployed today',
        'the pipeline ran successfully today',
        'continuous integration is very important',
        'the deployment was automated completely',
        // ── async / performance ──
        'async await simplifies asynchronous programming',
        'async await is very useful here',
        'the promise was resolved correctly',
        'the callback was executed successfully',
        'performance optimization reduced load time',
        'performance optimization is very important',
        'the application loads very fast now',
        'memory usage was reduced significantly',
        'the cache improved response time',
        // ── general cs phrases ──
        'i like programming in python daily',
        'i like coding new features always',
        'i like software development very much',
        'i like machine learning projects',
        'i like building web applications',
        'i like solving algorithmic problems',
        'i like writing clean code always',
        'i like computer science topics',
        'i like learning new technologies',
        'i like developing innovative solutions',
        'i enjoy programming every day',
        'i enjoy coding complex algorithms',
        'i enjoy software engineering work',
        'i enjoy building scalable systems',
        'i enjoy computer science challenges',
        'software engineering requires continuous learning',
        'software engineering is very challenging',
        'software engineering has many disciplines',
        'the application crashed due to memory',
        'the application is running well now',
        'the application will be released soon',
        'the application was updated yesterday',
        'object oriented programming promotes code reuse',
        'object oriented programming is very popular',
        'the package manager installs dependencies',
        'the package manager was configured today',
        'the loop iterates through array elements',
        'the loop was optimized for performance',
        'the variable stores user input data',
        'the variable was initialized correctly',
        'the string was parsed successfully',
        'the array was sorted in place',
        'the map stores key value pairs',
        'the set contains unique values only',
        'the interface defines the contract',
        'the class implements the interface',
        'the module exports several functions',
        'the import statement was added today',
        'the dependency was installed successfully',
        'the framework provides many useful tools',
        'the library was updated to latest',
        'the documentation was written clearly',
        'code review improves overall quality',
        'refactoring makes the code cleaner',
        'the sprint was completed on time',
        'the feature was shipped to production'
    ]
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { VOCABULARY, TRAINING_DATA };
}
