// Comprehensive vocabulary and training data for each user profile

const VOCABULARY = {
    sports: [
        // Common words
        'the', 'a', 'an', 'is', 'was', 'are', 'were', 'be', 'been', 'being',
        'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
        'can', 'may', 'might', 'must', 'to', 'of', 'in', 'on', 'at', 'by', 'for',
        'with', 'from', 'about', 'as', 'into', 'through', 'during', 'before', 'after',
        'i', 'you', 'he', 'she', 'it', 'we', 'they', 'my', 'your', 'his', 'her',
        'its', 'our', 'their', 'this', 'that', 'these', 'those', 'what', 'which',
        'who', 'when', 'where', 'why', 'how', 'and', 'or', 'but', 'if', 'because',
        'so', 'than', 'such', 'both', 'either', 'neither', 'not', 'only', 'just',
        'very', 'too', 'more', 'most', 'some', 'any', 'all', 'each', 'every', 'no',
        // Sports-specific vocabulary
        'game', 'match', 'play', 'player', 'team', 'score', 'goal', 'win', 'won', 'lose',
        'lost', 'victory', 'defeat', 'champion', 'championship', 'tournament', 'league',
        'season', 'coach', 'training', 'practice', 'field', 'court', 'stadium', 'arena',
        'ball', 'football', 'soccer', 'basketball', 'baseball', 'tennis', 'cricket',
        'hockey', 'rugby', 'volleyball', 'golf', 'swimming', 'running', 'racing',
        'athlete', 'athletic', 'sport', 'sports', 'competition', 'compete', 'competitive',
        'pass', 'shoot', 'kick', 'throw', 'catch', 'run', 'sprint', 'jump', 'dive',
        'tackle', 'defense', 'offense', 'attack', 'strategy', 'tactics', 'formation',
        'referee', 'umpire', 'penalty', 'foul', 'yellow', 'red', 'card', 'timeout',
        'quarter', 'half', 'period', 'inning', 'set', 'round', 'lap', 'race',
        'record', 'world', 'olympic', 'medal', 'gold', 'silver', 'bronze',
        'fitness', 'workout', 'exercise', 'gym', 'strength', 'speed', 'endurance',
        'performance', 'skill', 'technique', 'professional', 'amateur', 'draft',
        'contract', 'transfer', 'injury', 'injured', 'recovery', 'comeback',
        'amazing', 'incredible', 'fantastic', 'excellent', 'great', 'good', 'bad',
        'today', 'tomorrow', 'yesterday', 'tonight', 'now', 'then', 'always', 'never'
    ],
    
    baking: [
        // Common words
        'the', 'a', 'an', 'is', 'was', 'are', 'were', 'be', 'been', 'being',
        'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
        'can', 'may', 'might', 'must', 'to', 'of', 'in', 'on', 'at', 'by', 'for',
        'with', 'from', 'about', 'as', 'into', 'through', 'during', 'before', 'after',
        'i', 'you', 'he', 'she', 'it', 'we', 'they', 'my', 'your', 'his', 'her',
        'its', 'our', 'their', 'this', 'that', 'these', 'those', 'what', 'which',
        'who', 'when', 'where', 'why', 'how', 'and', 'or', 'but', 'if', 'because',
        'so', 'than', 'such', 'both', 'either', 'neither', 'not', 'only', 'just',
        'very', 'too', 'more', 'most', 'some', 'any', 'all', 'each', 'every', 'no',
        // Baking-specific vocabulary
        'bake', 'baking', 'baked', 'recipe', 'ingredient', 'ingredients', 'flour',
        'sugar', 'butter', 'egg', 'eggs', 'milk', 'cream', 'vanilla', 'chocolate',
        'yeast', 'salt', 'baking', 'powder', 'soda', 'cinnamon', 'nutmeg', 'ginger',
        'cake', 'bread', 'cookie', 'cookies', 'pie', 'pastry', 'muffin', 'muffins',
        'cupcake', 'cupcakes', 'brownie', 'brownies', 'tart', 'scone', 'biscuit',
        'dough', 'batter', 'mix', 'mixing', 'mixed', 'blend', 'whisk', 'beat',
        'fold', 'knead', 'roll', 'cut', 'shape', 'rise', 'proof', 'ferment',
        'oven', 'temperature', 'degrees', 'preheat', 'bake', 'baking', 'timer',
        'pan', 'sheet', 'tin', 'mold', 'bowl', 'mixer', 'spatula', 'whisk',
        'measuring', 'cup', 'spoon', 'tablespoon', 'teaspoon', 'gram', 'ounce',
        'sweet', 'savory', 'delicious', 'tasty', 'flavor', 'taste', 'texture',
        'moist', 'fluffy', 'crispy', 'crunchy', 'soft', 'tender', 'golden', 'brown',
        'frosting', 'icing', 'glaze', 'filling', 'topping', 'decoration', 'sprinkles',
        'layer', 'layers', 'slice', 'slices', 'piece', 'pieces', 'serve', 'serving',
        'fresh', 'homemade', 'scratch', 'perfect', 'easy', 'simple', 'quick',
        'traditional', 'classic', 'modern', 'artisan', 'gourmet', 'bakery',
        'turned', 'came', 'looks', 'smells', 'needs', 'requires', 'takes'
    ],
    
    cs: [
        // Common words
        'the', 'a', 'an', 'is', 'was', 'are', 'were', 'be', 'been', 'being',
        'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
        'can', 'may', 'might', 'must', 'to', 'of', 'in', 'on', 'at', 'by', 'for',
        'with', 'from', 'about', 'as', 'into', 'through', 'during', 'before', 'after',
        'i', 'you', 'he', 'she', 'it', 'we', 'they', 'my', 'your', 'his', 'her',
        'its', 'our', 'their', 'this', 'that', 'these', 'those', 'what', 'which',
        'who', 'when', 'where', 'why', 'how', 'and', 'or', 'but', 'if', 'because',
        'so', 'than', 'such', 'both', 'either', 'neither', 'not', 'only', 'just',
        'very', 'too', 'more', 'most', 'some', 'any', 'all', 'each', 'every', 'no',
        // CS-specific vocabulary
        'code', 'coding', 'program', 'programming', 'software', 'hardware', 'computer',
        'algorithm', 'data', 'structure', 'function', 'method', 'class', 'object',
        'variable', 'constant', 'array', 'list', 'dictionary', 'hash', 'map', 'set',
        'string', 'integer', 'float', 'boolean', 'null', 'undefined', 'type', 'types',
        'javascript', 'python', 'java', 'cpp', 'csharp', 'ruby', 'php', 'swift',
        'typescript', 'rust', 'go', 'kotlin', 'scala', 'language', 'languages',
        'framework', 'library', 'package', 'module', 'import', 'export', 'require',
        'react', 'angular', 'vue', 'node', 'express', 'django', 'flask', 'spring',
        'database', 'sql', 'nosql', 'mongodb', 'postgresql', 'mysql', 'redis',
        'api', 'rest', 'graphql', 'http', 'https', 'request', 'response', 'endpoint',
        'server', 'client', 'frontend', 'backend', 'fullstack', 'web', 'mobile',
        'app', 'application', 'development', 'developer', 'engineer', 'engineering',
        'debug', 'debugging', 'bug', 'error', 'exception', 'fix', 'test', 'testing',
        'unit', 'integration', 'deployment', 'production', 'staging', 'environment',
        'git', 'github', 'version', 'control', 'commit', 'push', 'pull', 'merge',
        'branch', 'repository', 'repo', 'clone', 'fork', 'issue', 'pr', 'review',
        'docker', 'kubernetes', 'container', 'cloud', 'aws', 'azure', 'gcp',
        'machine', 'learning', 'ai', 'artificial', 'intelligence', 'neural', 'network',
        'model', 'training', 'dataset', 'feature', 'optimization', 'performance',
        'memory', 'cpu', 'gpu', 'thread', 'process', 'async', 'await', 'promise',
        'callback', 'event', 'loop', 'stack', 'heap', 'garbage', 'collection',
        'compiled', 'runs', 'works', 'executes', 'returns', 'takes', 'needs'
    ]
};

// Expanded training sentences for each user profile
const TRAINING_DATA = {
    sports: [
        'i like sports very much',
        'i like football and basketball',
        'i like watching games live',
        'i like playing soccer daily',
        'i like competitive sports always',
        'i like training every morning',
        'i like athletic activities outdoors',
        'i like running marathons regularly',
        'i like team sports best',
        'i like championship tournaments always',
        'the game was amazing yesterday',
        'the game is starting soon',
        'the game will be exciting',
        'the game ended in victory',
        'the game was very competitive',
        'our team won the championship',
        'our team is playing well',
        'our team will win today',
        'our team has great players',
        'our team needs more practice',
        'the player scored three goals',
        'the player is very talented',
        'the player will join soon',
        'the player has incredible speed',
        'the player was injured yesterday',
        'training session starts at six',
        'training session is very important',
        'training session will be intense',
        'training session was productive today',
        'training session helps improve skills',
        'the coach announced new strategy',
        'the coach is very experienced',
        'the coach will make changes',
        'the coach has great tactics',
        'the coach was pleased today',
        'football match postponed due to rain',
        'football match is tomorrow night',
        'football match will be broadcast live',
        'football match was very exciting',
        'football match ended in draw',
        'basketball tournament begins next week',
        'basketball tournament is very competitive',
        'basketball tournament will have prizes',
        'basketball tournament was well organized',
        'basketball tournament attracts many teams',
        'the athlete broke world record',
        'the athlete is training hard',
        'the athlete will compete soon',
        'the athlete has amazing endurance',
        'the athlete was very fast',
        'olympic games are very exciting',
        'olympic games will start soon',
        'olympic games were held successfully',
        'olympic games attract global attention',
        'olympic games showcase athletic excellence',
        'tennis match lasted five hours',
        'tennis match is scheduled tomorrow',
        'tennis match will be challenging',
        'tennis match was incredibly intense',
        'tennis match ended at midnight',
        'the referee made controversial decision',
        'the referee is very experienced',
        'the referee will officiate tomorrow',
        'the referee was fair today',
        'the referee has good judgment',
        'team practice every morning at stadium',
        'team practice is mandatory today',
        'team practice will focus on defense',
        'team practice was very productive',
        'team practice helps build chemistry',
        'soccer player transferred to new club',
        'soccer player is very skilled',
        'soccer player will sign contract',
        'soccer player scored amazing goal',
        'soccer player has great technique',
        'the score was tied at halftime',
        'the score is very close',
        'the score will determine winner',
        'the score was surprising today',
        'the score reflects team performance',
        'running marathon requires great endurance',
        'running marathon is very challenging',
        'running marathon will test stamina',
        'running marathon was completed successfully',
        'running marathon attracts many participants',
        'swimming competition held in olympic pool',
        'swimming competition is tomorrow morning',
        'swimming competition will be exciting',
        'swimming competition was very close',
        'swimming competition showcases speed',
        'the defense was incredibly strong today',
        'the defense is well organized',
        'the defense will be tested',
        'the defense has improved significantly',
        'the defense was impenetrable yesterday',
        'penalty kick decided the final match',
        'penalty kick is very stressful',
        'penalty kick will determine winner',
        'penalty kick was perfectly executed',
        'penalty kick requires great skill',
        'cricket world cup starts in june',
        'cricket world cup is very popular',
        'cricket world cup will be exciting',
        'cricket world cup was held successfully',
        'cricket world cup attracts millions',
        'hockey team won gold medal',
        'hockey team is very strong',
        'hockey team will compete tomorrow',
        'hockey team has excellent players',
        'hockey team was victorious today',
        'volleyball serve was absolutely perfect',
        'volleyball serve is very powerful',
        'volleyball serve will be crucial',
        'volleyball serve was well executed',
        'volleyball serve requires good technique',
        'golf tournament played in beautiful weather',
        'golf tournament is very prestigious',
        'golf tournament will attract professionals',
        'golf tournament was well attended',
        'golf tournament showcases precision',
        'the quarterback threw amazing touchdown pass',
        'the quarterback is very talented',
        'the quarterback will lead team',
        'the quarterback has strong arm',
        'the quarterback was outstanding today',
        'baseball season opens next month',
        'baseball season is very long',
        'baseball season will be exciting',
        'baseball season was successful overall',
        'baseball season attracts many fans',
        'rugby match was physically demanding',
        'rugby match is tomorrow afternoon',
        'rugby match will be intense',
        'rugby match was very rough',
        'rugby match requires great strength',
        'fitness training improves athletic performance',
        'fitness training is essential daily',
        'fitness training will enhance skills',
        'fitness training was very effective',
        'fitness training helps prevent injuries',
        'the stadium was packed with fans',
        'the stadium is very large',
        'the stadium will host championship',
        'the stadium has great atmosphere',
        'the stadium was renovated recently',
        'sports injury requires proper recovery time',
        'sports injury is very unfortunate',
        'sports injury will need treatment',
        'sports injury was not serious',
        'sports injury can be prevented',
        'professional athletes train every single day',
        'professional athletes are very dedicated',
        'professional athletes will compete internationally',
        'professional athletes have rigorous schedules',
        'professional athletes were inspiring today',
        'the competition was fierce and intense',
        'the competition is starting now',
        'the competition will be challenging',
        'the competition has many participants',
        'the competition was won decisively',
        'i like sports very much',
        'i like football and basketball',
        'i like watching games live',
        'i like playing soccer daily',
        'i like competitive sports always',
        'i like training every morning',
        'i like athletic activities outdoors',
        'i like running marathons regularly',
        'i like team sports best',
        'i like championship tournaments always',
        'i enjoy sports competitions greatly',
        'i enjoy playing football regularly',
        'i enjoy watching basketball games',
        'i enjoy athletic training sessions',
        'i enjoy competitive matches always'
    ],
    
    baking: [
        'the cake turned out perfectly moist',
        'the cake is cooling down',
        'the cake will be decorated',
        'the cake has three layers',
        'the cake was delicious yesterday',
        'the cake looks absolutely beautiful',
        'the cake smells wonderful today',
        'the cake needs more frosting',
        'the cake requires careful handling',
        'the cake tastes amazing now',
        'baking bread requires patience and practice',
        'baking bread is very rewarding',
        'baking bread will take time',
        'baking bread has wonderful aroma',
        'baking bread was successful today',
        'baking bread needs proper kneading',
        'baking bread creates delicious results',
        'baking bread takes several hours',
        'chocolate chip cookies are my favorite',
        'chocolate chip cookies smell amazing',
        'chocolate chip cookies will be ready',
        'chocolate chip cookies taste delicious',
        'chocolate chip cookies were perfect yesterday',
        'chocolate chip cookies need more time',
        'chocolate chip cookies are very popular',
        'preheat the oven to three fifty',
        'preheat the oven before baking',
        'preheat the oven for best results',
        'preheat the oven at least ten',
        'preheat the oven until ready',
        'mix flour and sugar in bowl',
        'mix flour with butter carefully',
        'mix flour until well combined',
        'mix flour and eggs together',
        'mix flour with other ingredients',
        'the dough needs to rise overnight',
        'the dough is very sticky',
        'the dough will double in size',
        'the dough has risen perfectly',
        'the dough was kneaded thoroughly',
        'the dough should rest now',
        'the dough requires more flour',
        'vanilla extract adds wonderful flavor',
        'vanilla extract is essential ingredient',
        'vanilla extract will enhance taste',
        'vanilla extract has strong aroma',
        'vanilla extract was added carefully',
        'frosting should be smooth and creamy',
        'frosting is too thick',
        'frosting will be piped',
        'frosting has perfect consistency',
        'frosting was made fresh',
        'frosting needs more sugar',
        'homemade pastries taste much better',
        'homemade pastries are very special',
        'homemade pastries will impress guests',
        'homemade pastries have great flavor',
        'homemade pastries were enjoyed today',
        'the recipe calls for two eggs',
        'the recipe is very simple',
        'the recipe will yield twelve',
        'the recipe has clear instructions',
        'the recipe was followed exactly',
        'the recipe needs some adjustments',
        'knead the dough for ten minutes',
        'knead the dough until smooth',
        'knead the dough with both hands',
        'knead the dough on floured surface',
        'knead the dough gently today',
        'baking soda helps cakes rise properly',
        'baking soda is important ingredient',
        'baking soda will create bubbles',
        'baking soda has many uses',
        'baking soda was measured carefully',
        'fresh ingredients make all the difference',
        'fresh ingredients are very important',
        'fresh ingredients will improve taste',
        'fresh ingredients have better flavor',
        'fresh ingredients were used today',
        'the muffins came out golden brown',
        'the muffins are still warm',
        'the muffins will be served',
        'the muffins have blueberries inside',
        'the muffins were baked perfectly',
        'the muffins smell delicious now',
        'whisk butter and sugar until fluffy',
        'whisk butter with eggs thoroughly',
        'whisk butter until well combined',
        'whisk butter and cream together',
        'whisk butter for several minutes',
        'chocolate brownies are incredibly delicious',
        'chocolate brownies smell amazing today',
        'chocolate brownies will be cut',
        'chocolate brownies have fudgy texture',
        'chocolate brownies were enjoyed yesterday',
        'the pie crust was perfectly flaky',
        'the pie crust is very delicate',
        'the pie crust will be filled',
        'the pie crust has butter layers',
        'the pie crust was rolled thin',
        'measuring ingredients accurately is very important',
        'measuring ingredients carefully ensures success',
        'measuring ingredients will affect results',
        'measuring ingredients has been done',
        'measuring ingredients was done precisely',
        'cinnamon rolls smell absolutely amazing',
        'cinnamon rolls are still baking',
        'cinnamon rolls will be glazed',
        'cinnamon rolls have sweet filling',
        'cinnamon rolls were served warm',
        'the cupcakes need decorative frosting',
        'the cupcakes are cooling down',
        'the cupcakes will be decorated',
        'the cupcakes have vanilla flavor',
        'the cupcakes were baked today',
        'artisan bread takes time to perfect',
        'artisan bread is very crusty',
        'artisan bread will be sliced',
        'artisan bread has complex flavor',
        'artisan bread was made fresh',
        'baking temperature affects final texture',
        'baking temperature is very important',
        'baking temperature will determine doneness',
        'baking temperature has been set',
        'baking temperature was adjusted carefully',
        'the cookies spread too much unfortunately',
        'the cookies are perfectly crispy',
        'the cookies will be stored',
        'the cookies have chocolate chunks',
        'the cookies were baked yesterday',
        'sourdough starter needs daily feeding',
        'sourdough starter is very active',
        'sourdough starter will be used',
        'sourdough starter has tangy smell',
        'sourdough starter was refreshed today',
        'layer cake requires careful assembly',
        'layer cake is very impressive',
        'layer cake will be served',
        'layer cake has cream filling',
        'layer cake was decorated beautifully',
        'the scones were light and tender',
        'the scones are best served',
        'the scones will be enjoyed',
        'the scones have buttery flavor',
        'the scones were baked fresh',
        'baking from scratch is so rewarding',
        'baking from scratch takes more time',
        'baking from scratch will taste better',
        'baking from scratch has many benefits',
        'baking from scratch was worth it',
        'the tart filling was sweet and tangy',
        'the tart filling is very smooth',
        'the tart filling will set',
        'the tart filling has lemon flavor',
        'the tart filling was made fresh',
        'proper mixing technique prevents lumps',
        'proper mixing technique is essential',
        'proper mixing technique will ensure smoothness',
        'proper mixing technique has been used',
        'proper mixing technique was demonstrated today',
        'bakery quality results at home',
        'bakery quality bread is possible',
        'bakery quality pastries can be',
        'bakery quality cakes are achievable',
        'bakery quality desserts were made',
        'i like baking cakes daily',
        'i like making cookies often',
        'i like fresh bread always',
        'i like chocolate desserts best',
        'i like homemade pastries most',
        'i like decorating cupcakes creatively',
        'i like trying new recipes',
        'i like sweet treats always',
        'i like baking from scratch',
        'i like artisan bread making',
        'i enjoy baking delicious cakes',
        'i enjoy making fresh bread',
        'i enjoy decorating beautiful cupcakes',
        'i enjoy creating sweet desserts',
        'i enjoy homemade baking always'
    ],
    
    cs: [
        'the code compiled without any errors',
        'the code is running smoothly',
        'the code will be deployed',
        'the code has been tested',
        'the code was refactored yesterday',
        'the code works perfectly now',
        'the code needs more optimization',
        'the code requires better documentation',
        'debugging this issue took several hours',
        'debugging this problem is challenging',
        'debugging this bug will take',
        'debugging this error has been',
        'debugging this code was difficult',
        'javascript framework makes development easier',
        'javascript framework is very popular',
        'javascript framework will be updated',
        'javascript framework has many features',
        'javascript framework was chosen carefully',
        'the algorithm has linear time complexity',
        'the algorithm is very efficient',
        'the algorithm will be optimized',
        'the algorithm has been implemented',
        'the algorithm was designed carefully',
        'the algorithm works correctly now',
        'the algorithm needs better performance',
        'database query needs proper optimization',
        'database query is running slow',
        'database query will be improved',
        'database query has been executed',
        'database query was written yesterday',
        'database query returns correct results',
        'react components should be reusable',
        'react components are very flexible',
        'react components will be created',
        'react components have been tested',
        'react components were refactored today',
        'the api returns json formatted data',
        'the api is working correctly',
        'the api will be documented',
        'the api has many endpoints',
        'the api was deployed yesterday',
        'the api needs better error',
        'git commit message must be descriptive',
        'git commit message is very important',
        'git commit message will be written',
        'git commit message has been added',
        'git commit message was updated today',
        'machine learning model requires training data',
        'machine learning model is very accurate',
        'machine learning model will be deployed',
        'machine learning model has been trained',
        'machine learning model was improved yesterday',
        'machine learning algorithm works well',
        'machine learning techniques are powerful',
        'the function returns boolean value',
        'the function is very useful',
        'the function will be called',
        'the function has been tested',
        'the function was written yesterday',
        'the function takes two parameters',
        'the function needs better documentation',
        'python is great for data science',
        'python is very popular',
        'python will be used',
        'python has many libraries',
        'python was chosen carefully',
        'python code is readable',
        'docker container runs the application',
        'docker container is very lightweight',
        'docker container will be deployed',
        'docker container has been built',
        'docker container was created yesterday',
        'the server handles thousands of requests',
        'the server is running smoothly',
        'the server will be upgraded',
        'the server has high availability',
        'the server was restarted yesterday',
        'the server needs more resources',
        'unit tests ensure code quality',
        'unit tests are very important',
        'unit tests will be written',
        'unit tests have been passed',
        'unit tests were added today',
        'unit tests cover all cases',
        'async await simplifies asynchronous programming',
        'async await is very useful',
        'async await will be implemented',
        'async await has been used',
        'async await was introduced recently',
        'the repository has many open issues',
        'the repository is very active',
        'the repository will be updated',
        'the repository has good documentation',
        'the repository was created yesterday',
        'cloud deployment completed successfully today',
        'cloud deployment is very fast',
        'cloud deployment will be automated',
        'cloud deployment has been tested',
        'cloud deployment was done yesterday',
        'neural network achieved high accuracy',
        'neural network is very complex',
        'neural network will be trained',
        'neural network has many layers',
        'neural network was designed carefully',
        'the variable stores user input data',
        'the variable is very important',
        'the variable will be updated',
        'the variable has been initialized',
        'the variable was declared yesterday',
        'frontend framework improves user experience',
        'frontend framework is very modern',
        'frontend framework will be chosen',
        'frontend framework has many features',
        'frontend framework was updated today',
        'backend api provides necessary endpoints',
        'backend api is very robust',
        'backend api will be documented',
        'backend api has been tested',
        'backend api was deployed yesterday',
        'version control is essential for teams',
        'version control is very useful',
        'version control will be used',
        'version control has many benefits',
        'version control was implemented today',
        'the application crashed due to memory',
        'the application is running well',
        'the application will be released',
        'the application has been tested',
        'the application was updated yesterday',
        'software engineering requires continuous learning',
        'software engineering is very challenging',
        'software engineering will evolve constantly',
        'software engineering has many disciplines',
        'software engineering was studied thoroughly',
        'the loop iterates through array elements',
        'the loop is very efficient',
        'the loop will be optimized',
        'the loop has been tested',
        'the loop was written yesterday',
        'object oriented programming promotes code reuse',
        'object oriented programming is very popular',
        'object oriented programming will be used',
        'object oriented programming has many benefits',
        'object oriented programming was taught today',
        'the package manager installs dependencies',
        'the package manager is very useful',
        'the package manager will be updated',
        'the package manager has been configured',
        'the package manager was used yesterday',
        'performance optimization reduced load time',
        'performance optimization is very important',
        'performance optimization will be implemented',
        'performance optimization has been completed',
        'performance optimization was done today',
        'the exception was caught and handled',
        'the exception is very rare',
        'the exception will be logged',
        'the exception has been fixed',
        'the exception was thrown yesterday',
        'artificial intelligence transforms modern technology',
        'artificial intelligence is very powerful',
        'artificial intelligence will be used',
        'artificial intelligence has many applications',
        'artificial intelligence was discussed today',
        'the framework provides useful tools',
        'the framework is well documented',
        'the framework will be upgraded',
        'the framework has active community',
        'the framework was chosen carefully',
        'data structure is very efficient',
        'data structure will be implemented',
        'data structure has been optimized',
        'data structure was designed well',
        'i like programming in python',
        'i like coding new features',
        'i like software development always',
        'i like machine learning projects',
        'i like building web applications',
        'i like solving algorithmic problems',
        'i like writing clean code',
        'i like computer science topics',
        'i like learning new technologies',
        'i like developing innovative solutions',
        'i enjoy programming daily tasks',
        'i enjoy coding complex algorithms',
        'i enjoy software engineering work',
        'i enjoy building scalable systems',
        'i enjoy computer science challenges'
    ]
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { VOCABULARY, TRAINING_DATA };
}
